name: Compile Report
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install pandoc
        run: |
          curl -L https://github.com/jgm/pandoc/releases/download/3.1.10/pandoc-3.1.10-1-amd64.deb -o pandoc.deb
          sudo dpkg -i pandoc.deb
          sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-xetex
          
      - name: Compile Report
        run: |
          mkdir -p docs
          cat README.md >> pandoc-render-includes.md
          pandoc pandoc-render-includes.md -s -o docs/out.pdf --pdf-engine=xelatex
          

      - name: Push back PDF to repo
        run: |
          # configure git
          git config --global user.email "<>"
          git config --global user.name "Github Actions Bot"

          # commit upstream
          git add docs/out.pdf
          git commit -m "Updating Report"
          git restore .
          git push origin main
